apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-dilfuz-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    nginx.org/client-max-body-size: 2000m
  name: dilfuz-docker-ingress
spec:
  rules:
  - host: docker.dilfuz.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-dilfuz-service
          servicePort: {{ .Values.nexusport }}
      - path: /v2/
        backend:
          serviceName: nexus-dilfuz-service
          servicePort: {{ .Values.repo_port }}
  tls:
  - hosts:
    - docker.dilfuz.com
    secretName: tls-docker-prod-cert
